### ISSUE TITLE
Incompatible with 1.20+

### ISSUE THREAD

**Issue by Alkumist** [isaaclepes/MoreToolUpgrades#1]
unable to place items into smithing table 
![image_2023-09-02_170559155](https://github.com/isaaclepes/MoreToolUpgrades/assets/23058281/167b1364-8b86-45b5-993e-4deb1e5db487)

**Comment by isaaclepes** [comment]
1.20.x must have changed things. I will look into fixing this.

**Comment by isaaclepes** [comment]
v2.0.0 released.
